language: go

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

