language: go

arch:
  - amd64
  - arm64

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run v2
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./v2

after_success:
  - bash <(curl -s https://codecov.io/bash)

